#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("kalkulačka.Resource", IsApplication=true)]

namespace kalkulačka
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "13.1.0.5")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int ic_launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7F020000
			public const int activity_horizontal_margin = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int activity_vertical_margin = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int input_space = 2130837506;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F030000
			public const int ic_dashboard_black_24dp = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int ic_home_black_24dp = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int ic_notifications_black_24dp = 2130903042;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F040000
			public const int aboutLayout = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int calculateButton = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int calculateError = 2130968578;
			
			// aapt resource value: 0x7F040003
			public const int calculateLayout = 2130968579;
			
			// aapt resource value: 0x7F040004
			public const int container = 2130968580;
			
			// aapt resource value: 0x7F040005
			public const int convertButton = 2130968581;
			
			// aapt resource value: 0x7F040006
			public const int distanceValue = 2130968582;
			
			// aapt resource value: 0x7F040007
			public const int feedbackButton = 2130968583;
			
			// aapt resource value: 0x7F040008
			public const int feedbackLayout = 2130968584;
			
			// aapt resource value: 0x7F040009
			public const int feedbackvalue = 2130968585;
			
			// aapt resource value: 0x7F04000A
			public const int message = 2130968586;
			
			// aapt resource value: 0x7F04000B
			public const int navigation = 2130968587;
			
			// aapt resource value: 0x7F04000C
			public const int navigation_about = 2130968588;
			
			// aapt resource value: 0x7F04000D
			public const int navigation_calculate = 2130968589;
			
			// aapt resource value: 0x7F04000E
			public const int navigation_feedback = 2130968590;
			
			// aapt resource value: 0x7F04000F
			public const int navigation_myItens = 2130968591;
			
			// aapt resource value: 0x7F040010
			public const int navigation_table = 2130968592;
			
			// aapt resource value: 0x7F040011
			public const int noteSaveInput = 2130968593;
			
			// aapt resource value: 0x7F040012
			public const int notesLayout = 2130968594;
			
			// aapt resource value: 0x7F040013
			public const int saveNodeLayout = 2130968595;
			
			// aapt resource value: 0x7F040014
			public const int saveNoteButton = 2130968596;
			
			// aapt resource value: 0x7F040015
			public const int speedValue = 2130968597;
			
			// aapt resource value: 0x7F040016
			public const int tableLayout = 2130968598;
			
			// aapt resource value: 0x7F040017
			public const int tableRow1 = 2130968599;
			
			// aapt resource value: 0x7F040018
			public const int tableRow2 = 2130968600;
			
			// aapt resource value: 0x7F040019
			public const int tableRow3 = 2130968601;
			
			// aapt resource value: 0x7F04001A
			public const int textView1 = 2130968602;
			
			// aapt resource value: 0x7F04001B
			public const int textView10 = 2130968603;
			
			// aapt resource value: 0x7F04001C
			public const int textView11 = 2130968604;
			
			// aapt resource value: 0x7F04001D
			public const int textView12 = 2130968605;
			
			// aapt resource value: 0x7F04001E
			public const int textView13 = 2130968606;
			
			// aapt resource value: 0x7F04001F
			public const int textView14 = 2130968607;
			
			// aapt resource value: 0x7F040020
			public const int textView2 = 2130968608;
			
			// aapt resource value: 0x7F040021
			public const int textView3 = 2130968609;
			
			// aapt resource value: 0x7F040022
			public const int textView4 = 2130968610;
			
			// aapt resource value: 0x7F040023
			public const int textView5 = 2130968611;
			
			// aapt resource value: 0x7F040024
			public const int textView6 = 2130968612;
			
			// aapt resource value: 0x7F040025
			public const int textView7 = 2130968613;
			
			// aapt resource value: 0x7F040026
			public const int textView8 = 2130968614;
			
			// aapt resource value: 0x7F040027
			public const int textView9 = 2130968615;
			
			// aapt resource value: 0x7F040028
			public const int timeValue = 2130968616;
			
			// aapt resource value: 0x7F040029
			public const int tittleValue = 2130968617;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F050000
			public const int activity_main = 2131034112;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7F060000
			public const int menuReturn = 2131099648;
			
			// aapt resource value: 0x7F060001
			public const int navigation = 2131099649;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F070000
			public const int ic_launcher = 2131165184;
			
			// aapt resource value: 0x7F070001
			public const int ic_launcher_foreground = 2131165185;
			
			// aapt resource value: 0x7F070002
			public const int ic_launcher_round = 2131165186;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F080000
			public const int app_name = 2131230720;
			
			// aapt resource value: 0x7F080001
			public const int title_about = 2131230721;
			
			// aapt resource value: 0x7F080002
			public const int title_feedback = 2131230722;
			
			// aapt resource value: 0x7F080003
			public const int title_home = 2131230723;
			
			// aapt resource value: 0x7F080004
			public const int title_myItems = 2131230724;
			
			// aapt resource value: 0x7F080005
			public const int title_table = 2131230725;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F090000
			public const int AppTheme = 2131296256;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
